# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephemeral-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemeral-app
  template:
    metadata:
      labels:
        app: ephemeral-app
    spec:
      containers:
      - name: app
        image: ephemeral-app:latest # sed will replace this
        imagePullPolicy: Never # Critical for local Minikube builds
        ports:
        - containerPort: 8000
        env:
        - name: PR_NUMBER
          value: "REPLACE_ME_WITH_PR_NUMBER"
---
apiVersion: v1
kind: Service
metadata:
  name: ephemeral-service
spec:
  selector:
    app: ephemeral-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort # Use NodePort for local access instead of LoadBalancer
