name: Deploy Ephemeral PR Env (Local)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: [self-hosted, local-dev] # This tells GitHub to run the code on YOUR laptop
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Load to Minikube
        run: |
          PR_TAG="pr-${{ github.event.number }}"
          # We build directly into Minikube's Docker env so we don't even need to push to Docker Hub!
          eval $(minikube docker-env)
          docker build -t ephemeral-app:$PR_TAG .

      - name: Deploy to K8s
        run: |
          NAMESPACE="pr-${{ github.event.number }}"
          PR_TAG="pr-${{ github.event.number }}"
          
          # 1. Ensure the Namespace exists
          kubectl create namespace $NAMESPACE || true
          
          # 2. Fix the Image Tag (You already have this)
          sed -i "s|image: ephemeral-app:latest|image: ephemeral-app:$PR_TAG|g" k8s/deployment.yaml
          
          # 3. FIX: Inject the actual PR number into the environment variable
          sed -i 's|value: "REPLACE_ME_WITH_PR_NUMBER"|value: "'${{ github.event.number }}'"|g' k8s/deployment.yaml
          
          # 4. Apply the changes
          kubectl apply -f k8s/deployment.yaml -n $NAMESPACE
